{{- if eq .Values.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baseChart.fullName" . }}
  labels:
    {{- include "baseChart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "baseChart.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "baseChart.metadataLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "baseChart.serviceAccountName" . }}
      {{- with  .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ include "baseChart.fullName" . }}
          {{- if .Values.container.env }}
          env:
            {{- range .Values.container.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          {{- end }}
          envFrom:
            {{- with .Values.config }}
            - configMapRef:
                name: {{ include "baseChart.fullName" $ }}-{{ $.Values.image.appVersion | replace "." "-" }}-config
            {{- end }}
            {{- with .Values.secret }}
            - secretRef:
                name: {{ include "baseChart.fullName" $ }}-secret
            {{- end }}
          {{- with  .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.image.repository }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.appVersion }}"
          {{- else }}
          image: "registry-fortress.fareastone.com.tw/{{ include "baseChart.releaseName" . }}/{{ .Values.nameOverride }}:{{ .Values.image.appVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.container.ports }}
            - name: {{ default ( include "baseChart.fullName" $ ) .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- with .Values.container.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.container.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.container.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.container.preStop .Values.container.postStart }}
          lifecycle:
            {{- if .Values.container.postStart }}
            postStart:
              exec:
                command:
                  {{ toYaml .Values.container.postStart | nindent 18 }}
            {{- end }}
            {{- if .Values.container.preStop }}
            preStop:
              exec:
                command:
                  {{ toYaml .Values.container.preStop | nindent 18 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- if .Values.affinity }}
      {{- with .Values.affinity }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- include "baseChart.podAntiAffinity" . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
