{{- if eq .Values.environment "ocp" }}
{{- if .Values.route }}
{{- if .Values.route.enable }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "baseChart.fullName" . }}
  lables:
    {{- include "baseChart.labels" . | nindent 4 }}
    {{- with .Values.route.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ default (printf "%s.apps.bacchus.lafite.fareastone.com.tw" (include "baseChart.fullName" . )) .Values.route.host }}
  to:
    kind: Service
    name: {{ include "baseChart.fullName" . }}
    weight: 100
  port:
    targetPort: {{- with .Values.route.servicePort }}
  {{- with .Values.route.tls }}
  tls:
    termination: {{ .termination }}
    certificate: {{ .certificate | quote }}
    key: {{ .key | quote }}
    caCertificate: {{ .caCertificate | quote }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy }}
  {{- end }}
  {{- with .Values.route.wildcardPolicy }}
  wildcardPolicy: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
