{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "baseChart.fullName" . }}
spec:
  host: {{ include "baseChart.fullName" . }}.apps.bacchus.lafite.fareastone.com.tw
  to:
    kind: Service
    name: {{ include "baseChart.fullName" . }}
  {{- end }}