{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "baseChart.fullName" . }}-secret
  labels:
  {{- include "baseChart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secret }}
  {{ .name }}: {{ .value }}
  {{- end }}
{{- end}}