{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "baseChart.fullName" . }}-secret
type: Opaque
data:
  {{- range .Values.secret }}
  {{ .name }}: {{ .value }}
  {{- end }}
{{- end}}