{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "baseChart.fullName" . }}
  labels:
  {{- include "baseChart.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP"}}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP"}}
      name: {{ .name }}
    {{- end}}
  selector:
    {{- include "baseChart.selectorLabels" . | nindent 4 }}
  {{- end }}